In [ ]:
## Pandas is an open-source library that is built on top of NumPy library. It is a Python package that offers various data structures and operations for manipulating numerical data and time series. It is mainly popular for importing and analyzing data much easier. Pandas is fast and it has high-performance & productivity for users.

In [1]:
import pandas as pd

In [2]:
from pandas import Series , DataFrame

In [3]:
## Series
# Series is a one dimensional array - like object containing a sequence of values(of similar types to Numpy types) and an associated array of data labels is called Index

In [5]:
obj=pd.Series([1,2,3])

In [6]:
obj

0    1
1    2
2    3
dtype: int64

In [7]:
obj.values

array([1, 2, 3], dtype=int64)

In [8]:
obj.index

RangeIndex(start=0, stop=3, step=1)

In [9]:
obj2=pd.Series([1,2,3,4],index=["a","b","c","d"])

In [10]:
obj2

a    1
b    2
c    3
d    4
dtype: int64

In [11]:
obj2[obj2>2]

c    3
d    4
dtype: int64

In [12]:
obj2*2

a    2
b    4
c    6
d    8
dtype: int64

In [13]:
import numpy as np

In [15]:
np.exp(obj)

0     2.718282
1     7.389056
2    20.085537
dtype: float64

In [16]:
'b' in obj2

True

In [18]:
'e' in obj2

False

In [33]:
sdata={"ohio":1000,"Arizon":2000,"Florida":3000}

In [20]:
obj3=pd.Series(sdata)

In [21]:
obj3

ohio       1000
Arizon     2000
Florida    3000
dtype: int64

In [37]:
pd.isnull(obj3)

ohio       False
Arizon     False
Florida    False
dtype: bool

In [38]:
pd.notnull(obj3)

ohio       True
Arizon     True
Florida    True
dtype: bool

In [40]:
obj3.name='population'

In [42]:
obj3.index.name='state'

In [43]:
obj3

state
ohio       1000
Arizon     2000
Florida    3000
Name: population, dtype: int64

In [44]:
#DataFrame
## A data frame represents a rectangular table of data and contains an ordered collection of columns , each of which can be a different value type
#The data frame has both column and row indexes

In [45]:
data={'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
      'year':[2000,2001,2002,2001,2002,2003],
      'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}

In [46]:
frame=pd.DataFrame(data)

In [47]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [48]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [49]:
df=pd.DataFrame(data,columns=['year','state','pop'])  # To rearrange the columns

In [50]:
df

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [51]:
df1=pd.DataFrame(data,columns=['year','state','pop','debt'],index=['one','two','three','four','five','six'])

In [52]:
df1

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [53]:
df1.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [54]:
df1['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [56]:
df1.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [57]:
df1.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [58]:
df1.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [59]:
df1['debt']=1.6

In [60]:
df1

year   state  pop  debt
one    2000    Ohio  1.5   1.6
two    2001    Ohio  1.7   1.6
three  2002    Ohio  3.6   1.6
four   2001  Nevada  2.4   1.6
five   2002  Nevada  2.9   1.6
six    2003  Nevada  3.2   1.6

In [62]:
df1['debt']=np.arange(6)

In [63]:
df1

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4
six    2003  Nevada  3.2     5

In [64]:
val=pd.Series([-1.2,-1.5,-1.7],index=['two','four','five'])

In [67]:
df1['debt']=val

In [68]:
df1

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [69]:
pop={'Nevada':{2001:2.4,2002:2.9},'Ohio':{2000:1.5,2001:1.7,2002:3.6}}

In [70]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [72]:
df2=pd.DataFrame(pop)

In [73]:
df2

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [74]:
df2.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [75]:
df2=pd.DataFrame(df2,index=[2001,2002,2003])

In [76]:
df2

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [77]:
df2.index.name='Year'

In [78]:
df2

Nevada  Ohio
Year              
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [80]:
df2.columns.name='State'

In [81]:
df2

State  Nevada  Ohio
Year               
2001      2.4   1.7
2002      2.9   3.6
2003      NaN   NaN

In [82]:
df2.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, nan]])

In [83]:
df1.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [84]:
#Index Objects
#Pandas Index objects are responsible for holding the axis labels and other metadata

In [88]:
a=pd.DataFrame(range(3),index=['a','b','c'])

In [89]:
a

0
a  0
b  1
c  2

In [93]:
index=a.index

In [94]:
index

Index(['a', 'b', 'c'], dtype='object')

In [95]:
index[1:]

Index(['b', 'c'], dtype='object')

In [96]:
index[1]

'b'

In [97]:
0 in a

True

In [101]:
# Reindexing -It is an important method on pandas objects is reindex,which means to create a new object with the data confirmed on a new index

In [106]:
a=pd.Series([1,2,3],index=['x','y','v'])

In [107]:
a

x    1
y    2
v    3
dtype: int64

In [113]:
a1=a.reindex(['a','x','y','z''b','c','v'])

In [114]:
a1

a     NaN
x     1.0
y     2.0
zb    NaN
c     NaN
v     3.0
dtype: float64

In [115]:
frame=pd.DataFrame(np.arange(9).reshape((3,3)),
                index=['a','b','c'],
                columns=['Ohio','Texas','California'])

In [116]:
frame

Ohio  Texas  California
a     0      1           2
b     3      4           5
c     6      7           8

In [117]:
frame2=frame.reindex(['a','b','c','d'])

In [118]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   3.0    4.0         5.0
c   6.0    7.0         8.0
d   NaN    NaN         NaN

In [123]:
states=['Texas','Utah','California']

In [126]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
b      4   NaN           5
c      7   NaN           8

In [127]:
#Dropping entries from an Axis

In [128]:
obj=pd.Series(np.arange(5),index=['a','b','c','d','e'])

In [129]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [131]:
a=obj.drop('c')

In [132]:
a

a    0
b    1
d    3
e    4
dtype: int32

In [135]:
obj.drop(['d','c'])

a    0
b    1
e    4
dtype: int32

In [136]:
data=pd.DataFrame(np.arange(16).reshape(4,4),index=['India','Japan','SA','AUS'],columns=['a','b','c','d'])

In [137]:
data

a   b   c   d
India   0   1   2   3
Japan   4   5   6   7
SA      8   9  10  11
AUS    12  13  14  15

In [139]:
data.drop(['Japan','SA'])

a   b   c   d
India   0   1   2   3
AUS    12  13  14  15

In [140]:
data

a   b   c   d
India   0   1   2   3
Japan   4   5   6   7
SA      8   9  10  11
AUS    12  13  14  15

In [142]:
data.drop(['c'],axis=1)

a   b   d
India   0   1   3
Japan   4   5   7
SA      8   9  11
AUS    12  13  15

In [143]:
data

a   b   c   d
India   0   1   2   3
Japan   4   5   6   7
SA      8   9  10  11
AUS    12  13  14  15

In [145]:
data.drop(['a','b'],axis='columns')

c   d
India   2   3
Japan   6   7
SA     10  11
AUS    14  15

In [146]:
#Indexing ,Slection,Filtering

In [147]:
obj=pd.Series(np.arange(4),index=['a','b','c','d'])

In [148]:
obj

a    0
b    1
c    2
d    3
dtype: int32

In [151]:
obj['b']

1

In [152]:
obj[1]

1

In [153]:
obj[2:4]

c    2
d    3
dtype: int32

In [154]:
obj[['b','a','d']]

b    1
a    0
d    3
dtype: int32

In [155]:
obj[[1,3]]

b    1
d    3
dtype: int32

In [156]:
obj[obj<2]

a    0
b    1
dtype: int32

In [157]:
obj['b':'c']

b    1
c    2
dtype: int32

In [158]:
obj['b':'c']=5


In [159]:
obj

a    0
b    5
c    5
d    3
dtype: int32

In [160]:
data=pd.DataFrame(np.arange(16).reshape(4,4),
                 index=['Ohio','Colorado','Utah','NewYork'],
                 columns=['one','two','three','four'])

In [161]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [162]:
data['two']

Ohio         1
Colorado     5
Utah         9
NewYork     13
Name: two, dtype: int32

In [163]:
data[['three','one']]


three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
NewYork      14   12

In [170]:
data[1:3]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11

In [171]:
data[data['three']>3]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [172]:
data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
NewYork   False  False  False  False

In [173]:
data[data<5]=0

In [174]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [175]:
## Integer Indexes

In [176]:
ser=pd.Series(np.arange(3))

In [177]:
ser

0    0
1    1
2    2
dtype: int32

In [178]:
ser2=pd.Series(np.arange(3),index=['a','b','c'])

In [179]:
ser2

a    0
b    1
c    2
dtype: int32

In [180]:
ser[:1]

0    0
dtype: int32

In [181]:
ser.loc[:1]

0    0
1    1
dtype: int32

In [183]:
#Arithmatic and Data Alignment

In [184]:
s1=pd.Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])

In [185]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [186]:
s2=pd.Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g'])

In [187]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [188]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [189]:
df1=pd.DataFrame(np.arange(9).reshape((3,3)),columns=list('bcd'),index=['Ohio','Texas','Colorado'])

In [190]:
df2=pd.DataFrame(np.arange(12).reshape((4,3)),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])


In [191]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [192]:
df1

b  c  d
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [193]:
df2

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [194]:
df1=pd.DataFrame({'A':[1,2]})

In [195]:
df1

A
0  1
1  2

In [196]:
df2=pd.DataFrame({"B":[3,5]})

In [197]:
df2

B
0  3
1  5

In [198]:
df1-df2

A   B
0 NaN NaN
1 NaN NaN

In [199]:
#Arithmatic methods with fill values

In [200]:
df1=pd.DataFrame(np.arange(12).reshape((3,4)),columns=list('abcd'))

In [201]:
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [202]:

df2=pd.DataFrame(np.arange(20).reshape((4,5)),columns=list('abcde'))

In [203]:
df2

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [204]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [205]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [206]:
#Operations between Data Frame and Series

In [208]:
arr=np.arange(12).reshape((3,4))

In [210]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [211]:
arr[0]

array([0, 1, 2, 3])

In [212]:
arr-arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [213]:
frame=pd.DataFrame(np.arange(12).reshape((4,3)),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])

In [214]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [215]:
series=pd.Series(range(3),index=['b','e','f'])

In [216]:
series

b    0
e    1
f    2
dtype: int64

In [218]:
frame+series

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [219]:
series1=frame['d']

In [220]:
series1

Utah       1
Ohio       4
Texas      7
Oregon    10
Name: d, dtype: int32

In [221]:
#Sorting and Ranking

In [222]:
frame=pd.DataFrame(np.arange(8).reshape((2,4)),index=['three','one'],columns=['d','a','b','c'])

In [223]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [225]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [227]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [228]:
frame.sort_index(axis=1,ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [229]:
obj=pd.Series([4,7,-3,-2])

In [230]:
obj

0    4
1    7
2   -3
3   -2
dtype: int64

In [231]:
obj.sort_values()

2   -3
3   -2
0    4
1    7
dtype: int64

In [232]:
obj=pd.Series([4,np.nan,7,np.nan,-3,2])

In [233]:
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [234]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [235]:
frame=pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})

In [236]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [237]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [239]:
frame.sort_values(by=['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [240]:
#Axis Indexes with Duplicate Labels

In [241]:
obj=pd.Series(range(5),index=['a','a','b','b','c'])

In [242]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [244]:
obj.index.is_unique

False

In [245]:
obj['a']

a    0
a    1
dtype: int64

In [246]:
obj['b']

b    2
b    3
dtype: int64

In [248]:
obj.loc['b']

b    2
b    3
dtype: int64

In [249]:
#Summarizing and Computing Descriptive Statistics

In [250]:
df=pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],index=['a','b','c','d'],columns=['one','two'])

In [251]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [252]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [253]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [254]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [255]:
df.mean(axis='columns',skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [256]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [257]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [258]:
#Unique values ,Value Counts and Membership

In [259]:
obj=pd.Series(['c','a','d','a','a','b','b','c','c'])

In [260]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [261]:
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

In [262]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [263]:
mask=obj.isin(['b','c'])

In [264]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [265]:
data=pd.DataFrame({'Qu1':[1,3,4,3,4],'Qu2':[2,3,1,2,3],'Qu3':[1,5,2,4,4]})

In [266]:
data.apply(pd.value_counts).fillna(0)

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [267]:
#Group_by: Allows you to group together rows based off of a column and perform an aggregate function on them

In [268]:
data={'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],'Person':['A','B','C','D','E','F'],'Sales':[200,120,340,124,243,350]}

In [269]:
df=pd.DataFrame(data)
df

Company Person  Sales
0    GOOG      A    200
1    GOOG      B    120
2    MSFT      C    340
3    MSFT      D    124
4      FB      E    243
5      FB      F    350

In [270]:
by_company=df.groupby('Company')

In [272]:
print(by_company.mean())

         Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0


In [273]:
print(by_company.median())

         Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0


In [275]:
print(by_company.sum())

         Sales
Company       
FB         593
GOOG       320
MSFT       464


In [277]:
print(by_company.std())

              Sales
Company            
FB        75.660426
GOOG      56.568542
MSFT     152.735065


In [278]:
print(by_company.sum().loc['FB'])

Sales    593
Name: FB, dtype: int64


In [279]:
print(by_company.count())

         Person  Sales
Company               
FB            2      2
GOOG          2      2
MSFT          2      2


In [280]:
print(by_company.max())

        Person  Sales
Company              
FB           F    350
GOOG         B    200
MSFT         D    340


In [281]:
print(by_company.describe())

        Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0


In [282]:
#Concatination:It basically glues together dataframe.Dimensions should match
df1=pd.DataFrame({'A':[200],'B':[400]})
df2=pd.DataFrame({'C':[543],'D':[234]})
df3=pd.DataFrame({'E':[2456],'F':[9865]})

In [283]:
df1

A    B
0  200  400

In [284]:
df2

C    D
0  543  234

In [285]:
df3

E     F
0  2456  9865

In [286]:
pd.concat([df1,df2,df3],axis=0)

A      B      C      D       E       F
0  200.0  400.0    NaN    NaN     NaN     NaN
0    NaN    NaN  543.0  234.0     NaN     NaN
0    NaN    NaN    NaN    NaN  2456.0  9865.0

In [293]:
#Joining:Joining is convinient method for combining the columns of two potentially differentially index Dataframes 
#into a single resultant frame.
left=pd.DataFrame({'A':['A0','A1','A2','A3'],'B':['B1','B2','B3','B4']}) 
right=pd.DataFrame({'C':['C0','C1','C2','C3'],'D':['D1','D2','D3','D4']})

In [294]:
left.join(right,how='outer')

A   B   C   D
0  A0  B1  C0  D1
1  A1  B2  C1  D2
2  A2  B3  C2  D3
3  A3  B4  C3  D4

In [295]:
left.join(right)

A   B   C   D
0  A0  B1  C0  D1
1  A1  B2  C1  D2
2  A2  B3  C2  D3
3  A3  B4  C3  D4