In [1]:
#Numpy : Numpy is a linear algebra library for Python.It is one of the building block components .

#Numpy arrays essentially comes in two flavours 1)Vector 2)Matrices

#Vectors are 1-Dimensional arrays and Matrices are 2-Dimensional arrays

#Numpy array by using Python object such as list.NumPy is a general-purpose array-processing package. 
#It provides a high-performance multidimensional array object, and tools for working with these arrays. 
#It is the fundamental package for scientific computing with Python.It has bindings of C and C++ arrays

#What is an array¶
#An array is a data structure that stores values of same data type. 
#In Python, this is the main difference between arrays and lists. 
#While python lists can contain values corresponding to different data types, 
#arrays in python can only contain values corresponding to same data type

In [2]:
import numpy as np

In [3]:
my_list=[1,2,3,4,5]

In [4]:
array=np.array(my_list)

In [5]:
array

array([1, 2, 3, 4, 5])

In [6]:
type(array)

numpy.ndarray

In [7]:
#Multidimensional array

In [8]:
a=[1,2,3,4,5]
b=[2,3,4,5,6]
c=[2,3,4,5,6]

In [9]:
arr=np.array([a,b,c])

In [10]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6]])

In [11]:
type(arr)

numpy.ndarray

In [12]:
#Indexing

In [13]:
arr1=np.array([1,2,3,4,5])

In [14]:
arr1

array([1, 2, 3, 4, 5])

In [15]:
arr1[0]

1

In [16]:
arr1[3]

4

In [17]:
a=[1,2,3,4,5]
b=[6,7,8,9,10]
c=[1,3,5,7,9]

In [18]:
arr=np.array([a,b,c])

In [19]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 1,  3,  5,  7,  9]])

In [20]:
arr[1:,:2]

array([[6, 7],
       [1, 3]])

In [21]:
arr[:,3:]

array([[ 4,  5],
       [ 9, 10],
       [ 7,  9]])

In [22]:
arr=np.array([1,2,3,4,5])

In [23]:
arr[:3]=100

In [24]:
arr

array([100, 100, 100,   4,   5])

In [25]:
#create array and reshape
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [27]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
arr1

array([1, 2, 3, 4, 5])

In [29]:
arr1*arr1

array([ 1,  4,  9, 16, 25])

In [30]:
np.ones([2,5],dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [31]:
#Random Distribution

In [32]:
np.random.randn(3,3)

array([[ 1.09412129,  0.34481988, -0.57448008],
       [-0.3157227 ,  1.54707621,  0.90156943],
       [ 1.20467967,  0.5654803 ,  0.31626327]])

In [33]:
np.random.randint(0,100,25)

array([13,  2,  6, 15, 72, 58, 93, 84, 45, 74,  6, 10, 29, 27, 79, 64, 24,
       10, 75, 73, 51, 55, 14, 77, 36])

In [34]:
np.random.randint(0,100,8).reshape(4,2)

array([[70, 50],
       [62, 94],
       [32,  9],
       [80, 63]])

In [35]:
np.random.randint(0,100,8).reshape(2,4)

array([[ 3, 10, 61, 37],
       [ 0,  7, 20, 23]])

In [36]:
a=[1,2,3]

In [37]:
np.array(a)

array([1, 2, 3])

In [38]:
x=([1,2,3],[4,5,6],[8,9,10])

In [39]:
np.array(x)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [40]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [42]:
np.zeros(3)

array([0., 0., 0.])

In [43]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [44]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
np.zeros([13,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [48]:
np.eye(4)#Identity Matrix:(It is 2 dimensional square Matrix)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [49]:
np.random.rand(5) #It basically takes values from uniform distribution from 0 to 1

array([0.7112351 , 0.09481542, 0.19337521, 0.29486567, 0.16025395])

In [50]:
np.random.randn(1,2)

array([[1.19935786, 0.53943969]])

In [51]:
np.random.randint(1,99)

11

In [52]:
np.random.randint(1,100)#lower limit is 1 ,upper limit is 100 ,it select 1 random value between 1 to 100

63

In [53]:
np.random.randint(1,100,10)#lower limit is 1 ,upper limit is 100 ,it select 10 random value between 1 to 100

array([24, 11, 65, 61, 87, 22, 91, 22, 53, 30])

In [54]:
arr=np.arange(25))# display 0 to 24 numbers

SyntaxError: unmatched ')' (<ipython-input-54-492e1aaee10d>, line 1)

In [ ]:
arr

In [ ]:
arr.reshape(5,5)#Reshape method

In [ ]:
a=np.random.randint(0,50,10)

In [ ]:
a

In [ ]:
a.max()

In [ ]:
a.min()

In [ ]:
a.argmax()#argmax() indicates the location of maximum number

In [ ]:
a.argmin() #argmin() indicates the location of maximum number

In [ ]:
a.dtype

In [ ]:
a.shape

In [ ]:
arr=np.arange(0,11)

In [ ]:
arr

In [ ]:
arr[8]

In [ ]:
arr[1:5]

In [ ]:
arr[0:5]

In [ ]:
arr[:6]

In [ ]:
arr[5:]

In [ ]:
arr[0:5]

In [ ]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [ ]:
arr_2d

In [ ]:
arr_2d[0][0]

In [ ]:
arr_2d[1][1]

In [ ]:
arr_2d[2,1]

In [ ]:
arr_2d[:2,1:]

In [ ]:
arr_2d[:2]

In [ ]:
s=np.arange(0,10)

In [ ]:
s

In [ ]:
s<10

In [ ]:
s>6

In [ ]:
z=np.arange(50).reshape(5,10)

In [ ]:
z

In [ ]:
z[1:3]

In [ ]:
z[1:3,3:5]

In [ ]:
#Numpy Operations:

#Array with array operation :

In [ ]:
arr=np.arange(0,11)

In [ ]:
arr

In [ ]:
arr+arr

In [ ]:
arr-arr

In [ ]:
arr*arr

In [ ]:
arr+100

In [ ]:
arr-100

In [ ]:
arr*arr

In [ ]:
arr/arr

In [ ]:
1/arr

In [ ]:
arr*2

In [ ]:
#Universal array function:

In [ ]:
np.sqrt(arr)

In [ ]:
np.exp(arr)

In [ ]:
np.max(arr)

In [ ]:
np.sin(arr)

In [ ]:
np.log(arr)

In [ ]:
x=[1,2,3,4,5,6,5,4,3,2,1,1,2,22,4,3,4,5,]
x=np.array(x)
x

In [ ]:
type(x)

In [ ]:
x[0:10]

In [ ]:
x.shape

In [ ]:
x>4

In [ ]:
x[x>10]

In [ ]:

x = [1,2,3,4,5,6]
y = [7,8,9,10,11,12]


z = np.array([x,y])

In [ ]:
print(np.mean(z))
print(np.median(z))
print(np.mean(z[1,:]))
print(np.mean(z[:,1]))
print(np.std(z))
print(np.var(z))

In [ ]:
m1 = np.random.random((2,3))
m2 = np.random.random((2,3))

m1+m2

In [55]:
a=np.array([1,2,"Rohith"])

In [56]:
a

array(['1', '2', 'Rohith'], dtype='<U11')

In [57]:
type(a)

numpy.ndarray

In [58]:
a=([1,23,4],[2,3,4])

In [59]:
a

([1, 23, 4], [2, 3, 4])

In [60]:
np.array(a)

array([[ 1, 23,  4],
       [ 2,  3,  4]])

In [63]:
b=np.array([1,2,3],ndmin=5)

In [64]:
b

array([[[[[1, 2, 3]]]]])

In [65]:
np.mat(b)

matrix([[1, 2, 3]])

In [66]:
np.mat([1,2,3])

matrix([[1, 2, 3]])

In [67]:
##numpy.asarray

In [68]:
a=[1,2]

In [69]:
type(a)

list

In [70]:
np.array(a)

array([1, 2])

In [71]:
np.asarray(a) #Convert a list into an array:

array([1, 2])

In [72]:
b=[2,3]

In [73]:
np.array(b)

array([2, 3])

In [74]:
type(b)

list

In [75]:
type(np.array(b))

numpy.ndarray

In [76]:
a=np.array([1,2],dtype=float)

In [77]:
a

array([1., 2.])

In [79]:
a=np.array([1,2])

In [80]:
a

array([1, 2])

In [81]:
np.asarray(a) is a

True

In [82]:
np.asarray([1,2]) is a

False

In [83]:
np.asarray([1,2])

array([1, 2])

In [84]:
type(np.asarray([1,2]))

numpy.ndarray

In [85]:
##numpy.asanyarray

In [86]:
a=np.asanyarray([1,2,3])

In [87]:
a

array([1, 2, 3])

In [88]:
x=np.array([1,2,3])

In [89]:
x

array([1, 2, 3])

In [90]:
y=x

In [91]:
z=np.copy(x)

In [92]:
z

array([1, 2, 3])

In [93]:
y[0]=100

In [94]:
y

array([100,   2,   3])

In [95]:
x

array([100,   2,   3])

In [96]:
id(x[0])

723784289808

In [97]:
## data types

In [98]:
a=[1,2,3]

In [99]:
np.array(a)

array([1, 2, 3])

In [100]:
type(a)

list

In [102]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [103]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
matrix.ndim #Dimension of this matrix

2

In [106]:
matrix.size #Size of this matrix

9

In [107]:
matrix.shape

(3, 3)

In [108]:
matrix.dtype

dtype('int32')

In [110]:
b=np.array([[1,2,3],[4,5,6]])

In [111]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [112]:
# arange and linspace

In [115]:
np.array([2,6.5])

array([2. , 6.5])

In [116]:
list(range(5,16,2))

[5, 7, 9, 11, 13, 15]

In [117]:
list(range(50,-1,5))

[]

In [118]:
np.arange(0,11,2.5)# Numbers spaced apart by 2.5

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [119]:
np.linspace(4,10,50)

array([ 4.        ,  4.12244898,  4.24489796,  4.36734694,  4.48979592,
        4.6122449 ,  4.73469388,  4.85714286,  4.97959184,  5.10204082,
        5.2244898 ,  5.34693878,  5.46938776,  5.59183673,  5.71428571,
        5.83673469,  5.95918367,  6.08163265,  6.20408163,  6.32653061,
        6.44897959,  6.57142857,  6.69387755,  6.81632653,  6.93877551,
        7.06122449,  7.18367347,  7.30612245,  7.42857143,  7.55102041,
        7.67346939,  7.79591837,  7.91836735,  8.04081633,  8.16326531,
        8.28571429,  8.40816327,  8.53061224,  8.65306122,  8.7755102 ,
        8.89795918,  9.02040816,  9.14285714,  9.26530612,  9.3877551 ,
        9.51020408,  9.63265306,  9.75510204,  9.87755102, 10.        ])

In [120]:
## Matrix Creation

In [121]:
np.zeros(4)

array([0., 0., 0., 0.])

In [122]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [123]:
np.ones(4)

array([1., 1., 1., 1.])

In [124]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [125]:
np.ones((5,2,8))# Note matrix dimension specified by Tuples

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [126]:
5+np.ones((3,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [127]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [129]:
np.eye(10,10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [131]:
np.arange(3)

array([0, 1, 2])

In [132]:
np.arange(3.0)

array([0., 1., 2.])

In [133]:
np.arange(3,7,2)

array([3, 5])

In [134]:
np.linspace(2.0,3.0,num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [135]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [136]:
np.linspace(2.0, 3.0, num=9, retstep=True)

(array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   ]), 0.125)

In [146]:
a=np.arange(0,25).reshape(5,5)

In [147]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [148]:
np.diag(a)

array([ 0,  6, 12, 18, 24])

In [149]:
#Create a two-dimensional array with the flattened input as a diagonal.


In [151]:
np.diagflat([[1,2,3,4],[5,6,7,8]])

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 8]])

In [152]:
#An array with ones at and below the given diagonal and zeros elsewhere.

In [154]:
np.tri(3,5,1,dtype=int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [155]:
data2=[[1,2,3,4],[5,6,7,8]]

In [156]:
arr2=np.array(data2)

In [157]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [158]:
arr2.ndim

2

In [159]:
arr2.shape

(2, 4)

In [160]:
arr2.dtype

dtype('int32')

In [161]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [162]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [163]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [164]:
a=np.array([1,2,3],dtype=float)

In [165]:
a

array([1., 2., 3.])

In [167]:
b=np.array([1,2,3,4,5])

In [168]:
b

array([1, 2, 3, 4, 5])

In [169]:
b_float=b.astype(np.float)

In [171]:
b_float

array([1., 2., 3., 4., 5.])

In [172]:
b.astype(np.int)

array([1, 2, 3, 4, 5])

In [173]:
##Arithmetic and Numpy Array

In [175]:
x=np.array([[1,2,3],[4,5,6]])

In [176]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [177]:
x*x

array([[ 1,  4,  9],
       [16, 25, 36]])

In [178]:
x-x

array([[0, 0, 0],
       [0, 0, 0]])

In [179]:
x+x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [180]:
1/x

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [181]:
x*0.5

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [182]:
y=np.array([[1,4,1],[7,2,12]])

In [183]:
y

array([[ 1,  4,  1],
       [ 7,  2, 12]])

In [184]:
x>y

array([[False, False,  True],
       [False,  True, False]])

In [185]:
## Basic Indexing Slicing :


In [186]:
arr=np.arange(10)

In [187]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [188]:
arr[5]

5

In [189]:
arr[5:8]

array([5, 6, 7])

In [190]:
arr[5:8]=12

In [191]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [192]:
arr_slice=arr[5:8]

In [193]:
arr_slice

array([12, 12, 12])

In [194]:
arr_slice[1]=12345

In [195]:
arr_slice

array([   12, 12345,    12])

In [196]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [197]:
arr[:]=67

In [198]:
arr

array([67, 67, 67, 67, 67, 67, 67, 67, 67, 67])

In [199]:
arr_slice[:]=64

In [200]:
arr

array([67, 67, 67, 67, 67, 64, 64, 64, 67, 67])

In [201]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [202]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [203]:
arr2d[2]

array([7, 8, 9])

In [204]:
arr2d[0][2]

3

In [205]:
arr2d[0,2]

3

In [206]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [207]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [208]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [209]:
arr3d[0]=45

In [210]:
arr3d

array([[[45, 45, 45],
        [45, 45, 45]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [211]:
## Boolean Indexing

In [212]:
a=np.array(['Rohith','UK','London'])

In [213]:
a

array(['Rohith', 'UK', 'London'], dtype='<U6')

In [216]:
data=np.random.randn(3,10)

In [217]:
data

array([[ 0.63012072, -0.07695463, -0.10984772,  0.40169384,  2.53310736,
        -1.01603156, -1.06028417,  0.76651301, -1.17813958, -0.23220267],
       [ 0.32483477,  0.85877821,  0.50456563, -2.2547608 , -0.48263321,
        -0.74622368, -1.40925382,  0.09734568,  0.1190989 ,  1.3120363 ],
       [-0.83180334, -0.65839543,  1.47367508,  0.69520807,  1.27935611,
         0.29981295, -0.52536086,  1.36112242,  0.37482842,  0.95449721]])

In [222]:
data<0

array([[False,  True,  True, False, False,  True,  True, False,  True,
         True],
       [False, False, False,  True,  True,  True,  True, False, False,
        False],
       [ True,  True, False, False, False, False,  True, False, False,
        False]])

In [224]:
data[data<0]=0

In [225]:
data

array([[0.63012072, 0.        , 0.        , 0.40169384, 2.53310736,
        0.        , 0.        , 0.76651301, 0.        , 0.        ],
       [0.32483477, 0.85877821, 0.50456563, 0.        , 0.        ,
        0.        , 0.        , 0.09734568, 0.1190989 , 1.3120363 ],
       [0.        , 0.        , 1.47367508, 0.69520807, 1.27935611,
        0.29981295, 0.        , 1.36112242, 0.37482842, 0.95449721]])

In [226]:
#Fancy Indexing

In [227]:
arr=np.empty((8,4))

In [228]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [229]:
for i in range(8):
    arr[i]=i

In [230]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [231]:
o=np.arange(10).reshape(2,5)

In [232]:
o

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [233]:
o.T # Array transpose

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [234]:
arr=np.arange(16).reshape((2,2,4))

In [235]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [236]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [237]:
arr=np.random.randn(4,4)

In [238]:
arr

array([[ 0.80391364, -1.46979352,  0.80709746, -0.4364312 ],
       [-1.03517439,  0.16395062,  0.42568148,  0.2742194 ],
       [-0.33382074, -0.08227981, -0.78523776,  0.42286635],
       [-2.81909646, -0.84716964, -0.56748346, -1.08877022]])

In [239]:
arr>0

array([[ True, False,  True, False],
       [False,  True,  True,  True],
       [False, False, False,  True],
       [False, False, False, False]])

In [240]:
np.where(arr>0,2,-2)

array([[ 2, -2,  2, -2],
       [-2,  2,  2,  2],
       [-2, -2, -2,  2],
       [-2, -2, -2, -2]])

In [241]:
##Mathematical and Statistical Methods

In [244]:
arr=np.random.randn(54,3)

In [245]:
arr

array([[-0.4244978 , -1.71097094,  1.00502429],
       [-0.15202027, -1.0767119 ,  1.24715498],
       [ 0.6874126 , -0.11440783,  0.24019963],
       [-0.48710155,  1.37256094,  0.29560953],
       [ 1.45100708, -0.17918391, -0.58710254],
       [-0.07382921,  1.51508235,  0.20691605],
       [-0.59668112, -0.15696434,  0.02337899],
       [-0.67722896, -2.87999391, -0.73110559],
       [-1.34910018,  1.0865626 , -1.88482181],
       [-0.97518091, -0.7709724 ,  0.87270504],
       [ 1.80034675, -0.41446404,  1.11985616],
       [-0.34310395, -0.13630209, -2.36609767],
       [ 0.2401218 , -2.14669279,  0.00814067],
       [ 0.2842757 , -0.61770681,  0.59594581],
       [-1.02790571,  1.12681711, -0.15790866],
       [ 0.12109933,  0.28848671, -0.26558724],
       [-1.37018463, -0.30261499, -0.32747426],
       [ 1.00104205, -0.62835513,  0.01630476],
       [-0.46055284,  1.27052216,  1.34586719],
       [ 2.91003225,  0.81504758,  0.29979065],
       [-0.52808382, -0.30848515,  0.207

In [246]:
arr.mean()

-0.0451828465268967

In [247]:
np.mean(arr)

-0.0451828465268967

In [249]:
arr.sum()

-7.319621137357266

In [251]:
arr.mean(axis=1)# compute across columns

array([-0.37681482,  0.00614094,  0.27106813,  0.39368964,  0.22824021,
        0.54938973, -0.24342216, -1.42944282, -0.71578646, -0.29114942,
        0.83524629, -0.94850124, -0.63281011,  0.0875049 , -0.01966575,
        0.0479996 , -0.66675796,  0.1296639 ,  0.71861217,  1.34162349,
       -0.20973699, -0.02232356,  0.72184591,  1.57869323, -0.3187823 ,
       -0.37783593, -0.70198617, -0.07801754, -0.86074136,  0.21844094,
        1.05212952,  0.06836236, -0.82518504, -0.2909848 , -0.47162171,
       -0.14203646,  0.32081505, -0.3563953 ,  0.58472271,  0.01320298,
       -0.73987703,  0.15064425, -0.35943613,  0.07216686, -0.30548288,
        0.9127804 , -0.48963034, -0.21012845, -0.7694386 , -0.70806342,
        0.04043922, -0.10363749, -0.16413852,  1.04653465])

In [252]:
arr.sum(axis=0) # compute across rows

array([-0.44831496, -9.53565434,  2.66434817])

In [253]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])

In [254]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [255]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [256]:
arr=np.array([[0,1,2],[3,4,5],[6,7,8]])

In [257]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [258]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [259]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

In [260]:
### Methods for Boolean Array

In [261]:
arr=np.random.randn(100)

In [263]:
arr

array([ 4.04348416e-01, -8.29216403e-01,  1.36140749e+00,  1.11026056e+00,
       -8.16701555e-01,  2.24993396e-02,  5.77244350e-01,  5.20259548e-01,
       -7.56427440e-01,  5.09146982e-01, -1.39648939e+00,  1.89340013e+00,
        5.97549389e-01, -8.14158977e-01,  4.84113005e-01,  3.94867073e-01,
        6.89079336e-01, -5.50610907e-01, -3.37275835e-01, -3.05288107e-01,
       -4.46990429e-01, -3.14396577e-01,  6.21410102e-01,  1.08323601e-02,
       -1.59984229e-02,  8.88830332e-02,  9.43962853e-01, -4.79393577e-01,
       -2.79337663e-01, -7.79491297e-01,  1.20798769e-01,  1.23011692e+00,
       -1.07847761e+00, -1.05306970e+00, -5.43340739e-01,  1.18136054e+00,
        1.05240202e+00, -1.42537214e+00, -1.32349098e+00, -1.46668278e+00,
       -5.06083982e-01,  8.86982661e-01, -1.79148386e-01, -3.15959787e-01,
        2.28381428e-01,  1.70975205e+00, -2.88292515e-01, -2.11916833e+00,
       -1.52482250e+00, -1.56987562e+00, -5.26963132e-01,  1.03799999e-02,
        1.33337927e+00,  

In [264]:
(arr>0).sum()

54

In [265]:
##Sorting

In [266]:
arr=np.random.randn(6)

In [267]:
arr

array([ 0.46843938, -1.03905634,  0.79683999,  0.32398508, -0.76848929,
       -0.56198124])

In [268]:
arr.sort()

In [269]:
arr

array([-1.03905634, -0.76848929, -0.56198124,  0.32398508,  0.46843938,
        0.79683999])

In [270]:
arr=np.random.randn(5,3)

In [271]:
arr

array([[-1.31987404,  0.20224382,  0.31476537],
       [-1.05353562,  2.32499476, -1.35616687],
       [ 0.06520527, -0.56697017, -0.39286873],
       [-0.35998788, -1.90285756,  1.12883161],
       [ 0.09539618,  0.77655282, -0.36758602]])

In [272]:
arr.sort()

In [273]:
arr

array([[-1.31987404,  0.20224382,  0.31476537],
       [-1.35616687, -1.05353562,  2.32499476],
       [-0.56697017, -0.39286873,  0.06520527],
       [-1.90285756, -0.35998788,  1.12883161],
       [-0.36758602,  0.09539618,  0.77655282]])

In [274]:
large_arr=np.random.randn(100)

In [275]:
large_arr

array([-1.06642065, -0.37674258, -0.27733098, -0.01057248, -1.39704923,
       -0.01787635,  0.4595597 ,  1.45701571, -0.3896041 ,  0.13964562,
       -1.30400066, -0.14504285,  0.62549163, -1.07325751, -1.17157282,
       -0.76844565,  0.83726805,  1.03197114, -0.36550438,  1.54351186,
        0.31993403,  0.9195927 ,  1.06767038, -1.93622926,  0.14497714,
        0.60404618, -0.34866587,  1.46930678,  1.26503707, -1.22672024,
        0.41895476, -0.33651983, -0.54894205,  0.44707495,  0.82934792,
       -0.7319095 ,  0.33044211, -0.16049436,  1.40012967,  0.60776896,
       -1.22312775,  0.30308381,  0.26098171,  0.83436387,  1.56430744,
        0.05396837, -1.68097887, -0.6129843 , -0.33866579,  1.52234823,
       -0.13338699, -0.02655698,  1.03591466,  0.19590198,  0.77833356,
        2.57147022, -0.49876079,  0.52812163,  2.02898304, -1.91516548,
        0.27362719,  0.64409908,  0.37327698, -0.10280507, -0.62499578,
       -0.84589722,  0.62327858,  0.12892357,  0.45876695,  1.63

In [276]:
large_arr.sort()

In [277]:
large_arr

array([-1.9805028 , -1.93622926, -1.91516548, -1.68097887, -1.39704923,
       -1.30400066, -1.22672024, -1.22312775, -1.17871961, -1.17157282,
       -1.12720169, -1.07325751, -1.06642065, -0.84589722, -0.8185781 ,
       -0.79766018, -0.76844565, -0.73813129, -0.7319095 , -0.636047  ,
       -0.62499578, -0.6129843 , -0.54894205, -0.51526954, -0.49876079,
       -0.47217689, -0.41777899, -0.3896041 , -0.37674258, -0.36550438,
       -0.34866587, -0.33866579, -0.33651983, -0.27733098, -0.16049436,
       -0.14504285, -0.13338699, -0.12072193, -0.10280507, -0.02655698,
       -0.01787635, -0.01057248,  0.05396837,  0.06796384,  0.12892357,
        0.13964562,  0.14497714,  0.19590198,  0.26098171,  0.27362719,
        0.2981335 ,  0.30308381,  0.31993403,  0.33044211,  0.37327698,
        0.41895476,  0.44707495,  0.45876695,  0.4595597 ,  0.51265252,
        0.52812163,  0.54486748,  0.60404618,  0.60776896,  0.62327858,
        0.62549163,  0.63400826,  0.64409908,  0.73717115,  0.77

In [278]:
## Unique and Other Set Logic

In [279]:
a=np.array([1,1,4,2,3,5,'Rohith','London','London','UK'])

In [282]:
np.unique(a)

array(['1', '2', '3', '4', '5', 'London', 'Rohith', 'UK'], dtype='<U11')

In [283]:
##Linear Algebra

In [284]:
a=([[1,2,3],[4,5,6]])

In [285]:
b=([[3,2,1],[6,5,4]])

In [288]:
x=np.array(a)

In [289]:
y=np.array(b)

In [290]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [291]:
y

array([[3, 2, 1],
       [6, 5, 4]])

In [295]:
c=y.T

In [296]:
c

array([[3, 6],
       [2, 5],
       [1, 4]])

In [297]:
x.dot(c)

array([[10, 28],
       [28, 73]])

In [298]:
from numpy.linalg import inv,qr

In [299]:
X=np.random.randn(5,3)

In [300]:
X

array([[-1.74106147,  1.62214998, -0.43630346],
       [ 0.17746095, -1.25692684, -1.59876965],
       [ 1.11039287,  0.50335181,  0.41041333],
       [ 1.13409534, -0.60601292,  1.46866094],
       [ 0.04666409, -2.50837074, -0.46415037]])

In [301]:
mat=X.T.dot(X)

In [302]:
mat

array([[ 5.58410955, -3.29272729,  2.57557437],
       [-3.29272729, 11.12377413,  1.78260281],
       [ 2.57557437,  1.78260281,  5.28726471]])

In [303]:
inv(mat)

array([[ 0.37257368,  0.14732909, -0.2311631 ],
       [ 0.14732909,  0.15329126, -0.12345031],
       [-0.2311631 , -0.12345031,  0.34336102]])

In [304]:
mat.dot(inv(mat))

array([[ 1.00000000e+00,  0.00000000e+00,  1.11022302e-16],
       [-5.55111512e-17,  1.00000000e+00,  0.00000000e+00],
       [ 2.22044605e-16,  1.11022302e-16,  1.00000000e+00]])

In [305]:
## Pseudo Random Number Generation:

In [306]:
samples=np.random.normal(size=(4,4))

In [307]:
samples

array([[ 0.76401077,  1.40136477,  2.39407802,  0.31895962],
       [ 0.08950258, -0.40180495, -0.94444466, -0.06673905],
       [-0.72016591,  0.58969286,  0.60094497, -2.23752549],
       [-0.13749463,  0.02569342, -1.05727882,  0.10141727]])

In [308]:
a=np.random.seed(1234)

In [309]:
a

In [310]:
rng=np.random.RandomState(1234)

In [311]:
rng

RandomState(MT19937) at 0xA884DF2D40

In [312]:
rng.randn(10)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])